### ISSUE TITLE
Konu hakkında içerik bulunmadığında sayfa sayısı gösterimi

### ISSUE THREAD

**Issue by EmirBoyaci** [Chaisser/maaslisozluk-next#13]
- [x] konu hakkında bir içerik bulunmuyorsa sayfa sayısı 1/NaN geliyor.
- [x] sayfa sayısı geri ve ileri butonları ile değiştirilebiliyor ancak içerik bulunmadığı için bir etkisi olmuyor.

![image](https://user-images.githubusercontent.com/59085992/106353430-915c7100-62fb-11eb-9a56-cf3e6852868e.png)

**Comment by Chaisser** [comment]
hata düzeltildi
