### ISSUE TITLE
satoshi kazanım bugu

### ISSUE THREAD

**Issue by EmirBoyaci** [Chaisser/maaslisozluk-next#14]
- [ ] like butonuna iki defa basıldığında like'ı geri çekiyor ancak like edilen postu yazan kullanıcıya tekrardan 1 satoshi veriyor. sınırsız kere tekrar edilebiliyor.

![image](https://user-images.githubusercontent.com/59085992/106353596-c3220780-62fc-11eb-8ac1-ca50e65999d6.png)

**Comment by EmirBoyaci** [comment]
- [ ] kendi yazdığı yazıyı beğenememesi sağlanacak

**Comment by Chaisser** [comment]
client tarafında buttonı disable yaparak geçici olarak çözüm üretildi
