### ISSUE TITLE
Devamını oku hatası

### ISSUE THREAD

**Issue by yasin2dev** [Chaisser/maaslisozluk-next#15]
https://maaslisozluk.com/konu/gta-5 konusunda ikinci entry'ye bakılırsa eğer görüleceği üzere devamını oku olduğu için yanındaki like veya dislike gibi herhangi bir buton gözükmemekte.

![image](https://user-images.githubusercontent.com/56557752/106397776-23f63080-6420-11eb-9d4a-bb7b79fb0318.png)

**Comment by Chaisser** [comment]
Duplicate of #28
