### ISSUE TITLE
Boş bakiye sayfası

### ISSUE THREAD

**Issue by emresr** [Chaisser/maaslisozluk-next#20]
![screen](https://user-images.githubusercontent.com/24278628/106480210-2e660800-64bc-11eb-9a7a-215ff46a4b24.jpg)

**Comment by EmirBoyaci** [comment]
Ne gibi bir hata mevcut?

**Comment by Chaisser** [comment]
Hata kontrol edildi ancak bulunamadı. 

Arka plan rengi ve tablo özellikleri değiştirildi.
