### ISSUE TITLE
Dark Mode'da Uzun entry'de metin rengi siyah oluyor [stil hatası]

### ISSUE THREAD

**Issue by murateksiolu** [Chaisser/maaslisozluk-next#28]
Dark Mode'da Uzun entry yazınca metin rengi siyah oluyor ve gözükmüyor.   [Entry içerik yazısı ve devamını oku yazısı]

Örn. 
[https://maaslisozluk.com/konu/uzun-entry-deneme](url)

![image](https://user-images.githubusercontent.com/33262660/109396983-5f175100-7945-11eb-8958-bb28e69f81e7.png)

**Comment by Chaisser** [comment]
Artık uzun yazılar da kısa yazılar gibi gösteriliyor
