### ISSUE TITLE
Bazı öneriler.

### ISSUE THREAD

**Issue by ahmetsaglam714** [Chaisser/maaslisozluk-next#4]
- [x] Web sitesine giriş yapıldığında sol üstte yükleniyor yazısı var kaldırılabilir veyahut daha hoş bir yükleniyor ekranı getirilebilir.
- [x] Canlı takip et butonu aktifleştirilebilir
- [x] Bitcoinimiz 0'sa NaN yerine 0 yazdırılabilir
- [x] Varolan yazımızı düzenlemeye kalktığımızda , düzenlediğimiz yazıyı kaydetmeye çalıştığımızda bastığımız butonun adı "düzenle" değilde "düzenle ve kaydet" veya kaydet olabilir
- [x] Navbar elemanlarına ve bazı butonlara bastığımızda butonun,navbar elemanının etrafını bir border sarıyor kaldırılabilir.
- [x] en yeniler , spor , sinema gibi navbar elemanlarına tıklandığında yazılan yazılar orta kısımda gözükebilir
- [x] Navbar elemanlarına hoş bir hover verilebilir
- [x] Üst kısıma searchbox kısmı getirilebilir
- [x] Responsive hale getirilebilir

**Comment by Chaisser** [comment]
bitcoin sıfır olduğunda gelen NaN bulunamadı. Daha önceden düzeltilmişti. Yazı düzenlerken basılan button text değiştirildi.
