### ISSUE TITLE
Geliştirilebilir

### ISSUE THREAD

**Issue by CandenizErdal** [Chaisser/maaslisozluk-next#5]
- [x] Kayıt olma ekranında basit bir parola girildiğinde "Parolanız güçlü değil" gibi uyarılar verebilir.

**Comment by EmirBoyaci** [comment]
İncenelebilir: https://www.npmjs.com/package/check-password-strength

**Comment by Chaisser** [comment]
kayıt ekranında, 
şifre değiştirme ekranında, 
şifremi unuttum ekranında şifre güç ölçüm sistemi eklenmiştir. Artık şifrelerde ortalama düzeyde güvenliği sağlanmayan şifrelere izin verilmemektedir.
