### ISSUE TITLE
Sol taraftan konu değişimlerinde eklemek istedikleriniz kısmı olduğu gibi kalıyor

### ISSUE THREAD

**Issue by zaferaksakal** [Chaisser/maaslisozluk-next#7]
eklemek istedikleriniz kısmına bir şey yazıp ardından sol taraftan konuyu değiştirirseniz eklemek istedikleriniz temizlenmiyor

**Comment by Chaisser** [comment]
konu değişince sayfada tutulan bilgi artık siliniyor
