### ISSUE TITLE
Discord Webhook Bkz ve Link Etiketleri

### ISSUE THREAD

**Issue by EmirBoyaci** [Chaisser/maaslisozluk-next#8]
- [ ] discord maaşlı sözlük kanalına atılan webhooklarda bkz ve link taglerinin düzenlenmesi

![03462A94-7513-4430-8C1F-447170B5DBF3](https://user-images.githubusercontent.com/59085992/105632971-14e31180-5e67-11eb-942c-602c18c5cd1f.jpeg)
![46A825E0-D1E3-43B3-A4B6-B643DCFC7087](https://user-images.githubusercontent.com/59085992/105632974-17456b80-5e67-11eb-8659-55ef8499ae62.jpeg)

**Comment by Chaisser** [comment]
artık sadece açılan yeni konular discord webhook ile gönderiliyor.
